### ISSUE TITLE
(Roadmap) Drums

### ISSUE THREAD

**Issue by EliteAsian123** [YARC-Official/YARG#5]
### Drums Roadmap

- [ ] Notes
  - [x] Normal notes 
  - [x] Kick notes
  - [x] Double-kick notes
  - [x] Pro/cymbal notes
  - [ ] Soft/hard notes
  - [x] Scores
- [x] Starpower
  - [x] Starpower sections
  - [x] Starpower bar
  - [x] Starpower effects
- [ ] Extras
  - [ ] Drum fills
  - [ ] Big rock endings
- [ ] Difficulty downsampling
  - [ ] Easy
  - [ ] Medium
  - [ ] Hard
- [x] Controllers
  - [x] MIDI drums
  - [x] Normal RB drums (4-lane)
  - [x] Normal GH drums (5-lane) (#28)

**Comment by binarygeek119** [comment]
kick assistants where if you hit the note it counts but if you miss it no big deal. also doesnt mute audio when missed

**Comment by EliteAsian123** [comment]
This is obsolete. Please refer to https://yarg.youtrack.cloud/agiles/147-7/current
